binance:
  real-time-url: wss://fstream.binance.com
  current-price-stream-name: markPrice
  symbol: btcusdt

spring:
  kafka:
    bootstrap-servers: kafka:29092, kafka2:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://schema-registry:8085
      auto.register.schema: true

kafka:
  bitcoin-topic: bitcoin-current-prices-topic
  etherium-topic: etherium-current-prices-topic
