coin-market:
  real-time-url: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest
  token: 424c7e24-0daa-4173-83ad-5e7b34b5073a
  convert: USD
  symbol: BTC,ETH

scheduler:
  enabled: true
  interval: "0 * * * * ?"

spring:
  kafka:
    bootstrap-servers: kafka:29092, kafka2:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  bitcoin-topic: bitcoin-topic
  etherium-topic: etherium-topic


